apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-mcp
  namespace: agent-execution
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fleet-mcp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fleet-mcp
    spec:
      containers:
      - env:
        - name: S20_URL
          value: http://10.0.0.20:11434
        - name: S10E_URL
          value: http://10.0.0.10:11434
        image: docker.io/library/fleet-mcp:latest
        imagePullPolicy: Never
        name: fleet-mcp
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

